// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFPEk1yr_-lG5kU9gyEXmYACDKC2DGh9U',
    appId: '1:948639542031:web:2da43437999a991a562c7a',
    messagingSenderId: '948639542031',
    projectId: 'conectasoc-859f2',
    authDomain: 'conectasoc-859f2.firebaseapp.com',
    storageBucket: 'conectasoc-859f2.firebasestorage.app',
    measurementId: 'G-Y3BTVDH9HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnbQgbpWTWm1kOxJli_8ez5bVUAH_oHs',
    appId: '1:948639542031:android:be770cdfdf8043fb562c7a',
    messagingSenderId: '948639542031',
    projectId: 'conectasoc-859f2',
    storageBucket: 'conectasoc-859f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNOnf23neJre0mx1iDvJaX381Su1JH6I',
    appId: '1:948639542031:ios:8966ae008fa3fdbf562c7a',
    messagingSenderId: '948639542031',
    projectId: 'conectasoc-859f2',
    storageBucket: 'conectasoc-859f2.firebasestorage.app',
    iosClientId:
        '948639542031-iljdn9vm2c43cabpf1cr3p9u47gscn5t.apps.googleusercontent.com',
    iosBundleId: 'es.eglos.conectasoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_IOS_API_KEY',
    appId: 'TU_MACOS_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'tu-project-id',
    storageBucket: 'tu-project-id.appspot.com',
    iosBundleId: 'es.eglos.conectasoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TU_WEB_API_KEY',
    appId: 'TU_WINDOWS_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'tu-project-id',
    authDomain: 'tu-project-id.firebaseapp.com',
    storageBucket: 'tu-project-id.appspot.com',
  );
}
